"use client";
import {useEffect,useMemo,useState} from "react";
import {Button,Input,Typography} from "shivanya-ui";
import {useAuth} from "@/lib/auth";
import {memoryApi} from "@/lib/api";
import type {MemoryItem,MemoryResource} from "@/lib/types";
const labels:Record<MemoryResource,string>={notes:"Notes",tasks:"Tasks",lists:"Lists",goals:"Goals",routines:"Routines",reminders:"Reminders",tags:"Tags"};
export default function MemoryPage({resource}:{resource:MemoryResource}){const {client}=useAuth();const [items,setItems]=useState<MemoryItem[]>([]);const [title,setTitle]=useState("");const [content,setContent]=useState("");const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
async function load(){setLoading(true);try{const result=await memoryApi<MemoryItem[]|{results:MemoryItem[]}>(client,resource+"/");setItems(Array.isArray(result)?result:result.results);setError("");}catch(err){setError(err instanceof Error?err.message:"Unable to load Memory.");}finally{setLoading(false);}}
useEffect(()=>{void load();},[resource]);
const filtered=useMemo(()=>{const query=search.trim().toLowerCase();return query?items.filter(item=>(String(item.title)+" "+String(item.content||"")).toLowerCase().includes(query)):items;},[items,search]);
async function create(){if(!title.trim())return;setSaving(true);try{const created=await memoryApi<MemoryItem>(client,resource+"/",{method:"POST",body:JSON.stringify({title:title.trim(),content})});setItems(current=>[created,...current]);setTitle("");setContent("");}catch(err){setError(err instanceof Error?err.message:"Unable to create item.");}finally{setSaving(false);}}
async function remove(id:number){await memoryApi(client,resource+"/"+id+"/",{method:"DELETE"});setItems(current=>current.filter(item=>item.id!==id));}
return <section className="memory-page"><div className="memory-page-header"><div><Typography as="h1" variant="h2" weight="semibold">{labels[resource]}</Typography><Typography as="p" variant="body" color="secondary">Organize your personal information in Memory.</Typography></div></div><div className="memory-toolbar"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={"Search "+labels[resource].toLowerCase()+"..."} /></div><div className="memory-create"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder={"New "+labels[resource].toLowerCase().slice(0,-1)} />{resource!=="tags"&&<textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Content" />}<Button disabled={saving||!title.trim()} onClick={create}>{saving?"Saving...":"Create"}</Button></div>{error&&<Typography as="p" variant="bodySmall" color="secondary">{error}</Typography>}{loading?<div className="memory-loading">Loading...</div>:<div className="memory-list">{filtered.map(item=><article className="memory-card" key={item.id}><div><Typography as="h3" variant="body" weight="semibold">{item.title}</Typography>{item.content&&<Typography as="p" variant="bodySmall" color="secondary">{String(item.content)}</Typography>}</div><Button variant="outline" onClick={()=>void remove(item.id)}>Delete</Button></article>)}{!filtered.length&&<div className="memory-empty">Nothing here yet.</div>}</div>}</section>;}
