"use client";
import {useEffect,useMemo,useState} from "react";
import {Button,Input,Modal,Typography} from "shivanya-ui";
import {useAuth} from "@/lib/auth";
import {memoryApi} from "@/lib/api";
import {trackMemoryEvent} from "@/lib/analytics";
import type {MemoryItem,MemoryResource} from "@/lib/types";
const labels:Record<MemoryResource,string>={notes:"Notes",tasks:"Tasks",lists:"Lists",goals:"Goals",routines:"Routines",reminders:"Reminders",tags:"Tags"};
const createPayload=(resource:MemoryResource,title:string,content:string)=>resource==="tags"?{name:title}:{title,content};
export default function MemoryPage({resource}:{resource:MemoryResource}){const {client}=useAuth();const [items,setItems]=useState<MemoryItem[]>([]);const [selected,setSelected]=useState<MemoryItem|null>(null);const [title,setTitle]=useState("");const [content,setContent]=useState("");const [search,setSearch]=useState("");const [filter,setFilter]=useState("all");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const label=labels[resource];
async function load(){setLoading(true);try{const query=new URLSearchParams();if(search.trim())query.set("q",search.trim());if(filter==="favorites")query.set("favorite","true");if(filter==="locked")query.set("locked","true");if(filter==="archived")query.set("archived","true");const result=await memoryApi<MemoryItem[]>(client,resource+"/?"+query);setItems(result);setError("");}catch(err){setError(err instanceof Error?err.message:"Unable to load "+label+".");}finally{setLoading(false);}}
useEffect(()=>{const id=window.setTimeout(()=>void load(),180);return()=>window.clearTimeout(id);},[resource,search,filter]);
const visible=useMemo(()=>items,[items]);
function reset(){setTitle("");setContent("");setSelected(null);}
async function save(){if(!title.trim())return;setSaving(true);try{const path=selected?resource+"/"+selected.id+"/":resource+"/";const result=await memoryApi<MemoryItem>(client,path,{method:selected?"PATCH":"POST",body:JSON.stringify(createPayload(resource,title,content))});setItems(current=>selected?current.map(item=>item.id===result.id?result:item):[result,...current]);trackMemoryEvent(selected?"memory_update":"memory_create",{resource,id:result.id});reset();}catch(err){setError(err instanceof Error?err.message:"Unable to save item.");}finally{setSaving(false);}}
function edit(item:MemoryItem){setSelected(item);setTitle(String(item.title||item.name||""));setContent(String(item.content||""));}
async function action(id:number,actionName:string){try{const result=await memoryApi<MemoryItem>(client,resource+"/"+id+"/"+actionName+"/",{method:"POST"});if(actionName==="trash")setItems(current=>current.filter(item=>item.id!==id));else setItems(current=>current.map(item=>item.id===id?result:item));trackMemoryEvent("memory_update",{resource,id,action:actionName});}catch(err){setError(err instanceof Error?err.message:"Unable to update item.");}}
return <section className="memory-page"><div className="memory-page-header"><div><Typography as="h1" variant="h2" weight="semibold">{label}</Typography><Typography as="p" variant="body" color="secondary">Create, manage, search, organize and protect your {label.toLowerCase()}.</Typography></div><Button onClick={()=>{reset();setSelected({id:0} as MemoryItem)}}>Create</Button></div><div className="memory-toolbar"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={"Search "+label.toLowerCase()+"..."} /><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="favorites">Favorites</option><option value="locked">Locked</option><option value="archived">Archived</option></select></div>{error&&<div className="memory-error">{error}</div>}{loading?<div className="memory-loading">Loading...</div>:<div className="memory-list">{visible.map(item=><article className="memory-card" key={item.id}><div className="memory-card-content"><Typography as="h3" variant="body" weight="semibold">{String(item.title||item.name||"Untitled")}</Typography>{item.content&&<Typography as="p" variant="bodySmall" color="secondary">{String(item.content)}</Typography>}<div className="memory-meta">{item.favorite?"Favorite ":""}{item.locked?"Locked ":""}{item.completed?"Completed":""}</div></div><div className="memory-actions"><Button variant="outline" onClick={()=>edit(item)}>Edit</Button><Button variant="outline" onClick={()=>void action(item.id,"favorite")}>Favorite</Button>{(resource==="tasks"||resource==="goals")&&<Button variant="outline" onClick={()=>void action(item.id,"complete")}>{item.completed?"Undo":"Complete"}</Button>}<Button variant="outline" onClick={()=>void action(item.id,"archive")}>Archive</Button><Button variant="outline" onClick={()=>void action(item.id,"trash")}>Trash</Button></div></article>)}{!visible.length&&<div className="memory-empty">Nothing here yet.</div>}</div>}<Modal open={Boolean(selected)} onClose={reset} title={selected?.id?"Edit "+label.slice(0,-1):"Create "+label.slice(0,-1)} size="md" radius="lg"><div className="memory-modal-body"><Input label={resource==="tags"?"Tag name":"Title"} value={title} onChange={e=>setTitle(e.target.value)} /><Input label="Content" value={content} onChange={e=>setContent(e.target.value)} /><div className="memory-modal-actions"><Button variant="outline" onClick={reset}>Cancel</Button><Button disabled={saving||!title.trim()} onClick={()=>void save()}>{saving?"Saving...":"Save"}</Button></div></div></Modal></section>;}
